### ISSUE TITLE
AttributeError: 'Parameter' object has no attribute 'denom'

### ISSUE THREAD

**Issue by feevos** [ItzikMalkiel/MTAdam#1]
Hi, 

thank you for this repo. I tried to use your optimizer, and I get the error: 

```python
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    optimizer.step(loss_array, ranks, None)
  File "/home/fdiakogiannis/Software/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/fdiakogiannis/Software/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/fdiakogiannis/Projects/OI-FD-dev/src/training_scripts/nbeatsxx/model_v3_quantile_to/mtadam.py", line 64, in step
    self.update_weights(loss_array, ranks)
  File "/home/fdiakogiannis/Projects/OI-FD-dev/src/training_scripts/nbeatsxx/model_v3_quantile_to/mtadam.py", line 153, in update_weights
    max_denom = p.denom[0]
AttributeError: 'Parameter' object has no attribute 'denom'
srun: error: hyades03: task 0: Exited with exit code 1

```

I tried to use MTAdam to combine L1Loss and BCELoss. The relative code entries I use are: 

```python
# Balanced Adam optimizer 
from mtadam import *

...
optimizer = MTAdam(net.parameters(), lr=0.001)
...
# The first loss is L1 the second BCE Loss, as given by torch.nn. 
loss_array = [criterion(ypreds, ylabel), criterion_pp(to_preds,to_label)]
ranks = [1]*len(loss_array)
optimizer.step(loss_array, ranks, None)
```

any ideas on how to overcome the problem? I am using the NGC NVIDIA container for pytorch. 

Kind regards,
Foivos

**Comment by leto19** [comment]
Hi, not sure if you ever figured this out, but the solution I found was removing unused layers from the model initialisation.

**Comment by huytuong010101** [comment]
same problem

**Comment by pyretttt** [comment]
They have got only one check `if p.grad is None`
Add the same inside second top level loop inside `update_weights` func
